### ISSUE TITLE
File upload not rendering

### ISSUE THREAD

**Issue by mebibou** [scottie1984/swagger-ui-express#185]
I am using swagger-jsdoc to define my swagger paths and on one particular endpoint I need to do file upload. The swagger doc looks like this:

```javascript
/**
 * @swagger
 *
 * paths:
 *   /files:
 *     post:
 *       summary: Upload files for processing
 *       requestBody:
 *         required: true
 *         content:
 *           multipart/form-data:
 *             schema:
 *               type: object
 *               properties:
 *                 file:
 *                   type: array
 *                   items:
 *                     type: string
 *                     format: binary
 *       responses:
 *         200:
 *           $ref: '#/components/responses/NoContent'
 *         401:
 *           $ref: '#/components/responses/UnauthorizedError'
 *         500:
 *           $ref: '#/components/responses/UnexpectedError'
 */
```
When I hit "Try It Out" in swagger UI, I have a warning in the console `Could not find component: JsonSchema_string_binary` and the UI does not show an input to choose files:

![Screen Shot 2020-05-17 at 9 33 34 AM](https://user-images.githubusercontent.com/305342/82138536-858a5680-9821-11ea-8712-26562e96e7b0.png)

**Comment by BePo65** [comment]
Oh, i do also wait for the solutuion to this problem.

I think that this is the known problem solved in [ swagger-api/swagger-ui issue #4600 ](https://github.com/swagger-api/swagger-ui/issues/4600). To transfer this solution to this package here, the dependeny 'swagger-ui-dist' should be updated to v3.26.0 (the latest release).

**Comment by mebibou** [comment]
@BePo65 thanks, `npm install swagger-ui-dist@latest` will work for now until a new release with update dist is available

**Comment by KeitelDOG** [comment]
Is this solved? Cause I'm using latest version`"swagger-ui-express": "^4.1.6"` and it still does not parse files correctly.

Should I add `swagger-ui-dist@latest` while waiting?

**Comment by scottie1984** [comment]
Please use ```npm install --save swagger-ui-dist@latest```

When installing swagger-ui-express it will pull in the latest version of swagger-ui-dist.

**Comment by NaturalAI-InspireXT** [comment]
This problem still persists, with the following packages 

{
    "swagger-jsdoc": "^6.0.8",
    "swagger-ui-express": "^4.1.6"
}

**Comment by devanshu-appinventers** [comment]
still there in
{
"swagger-ui-express": "^5.0.0"
}
