### ISSUE TITLE
support of OpenAPI 3.1.* ?

### ISSUE THREAD

**Issue by yfhui** [scottie1984/swagger-ui-express#274]
currently this is using "swagger-ui-dist": "^3.18.1" which according to my understanding, this does not support the new openAPI 3.1.

Consider update to swagger-ui v4 for support of openAPI 3.1 (see this [issue](https://github.com/swagger-api/swagger-ui/issues/5891) in swagger-ui)

**Comment by scottie1984** [comment]
should be fixed now as part of https://github.com/scottie1984/swagger-ui-express/releases/tag/4.2.0

**Comment by yfhui** [comment]
great! thanks for the quick response!

**Comment by yfhui** [comment]
@scottie1984 I think I may have overread something, swagger UI v4.x actually still does not offically support openAPI 3.1 yet. See this line in the [code](https://github.com/swagger-api/swagger-ui/blob/cc408812fc927e265da158bf68239530740ab4cc/src/core/plugins/oas3/helpers.jsx#L13) at the master branch. But the updage to v4 still be good, no need to revert anything.

**Comment by StephanBijzitter** [comment]
This issue should be re-opened, the line guarding against 3.1 is still in place
